In [2]:
import torch
# 创建一个5x3的未初始化的Tensor
x = torch.empty(5, 3)
print(x)

tensor([[-3.2538e-19,  1.6647e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [3]:
# 创建一个5x3的随机初始化的Tensor
x = torch.rand(5, 3)
print(x)

tensor([[0.8380, 0.7807, 0.6941],
        [0.9632, 0.5328, 0.5848],
        [0.5598, 0.6569, 0.1787],
        [0.9133, 0.8901, 0.2981],
        [0.8154, 0.3126, 0.1799]])


In [4]:
# 创建一个5x3的long型全0的Tensor
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

# 使用全1数据创建一个2x3x4的Tensor
tp = torch.ones((2, 3, 4), dtype=torch.int)
print(tp)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=torch.int32)


In [5]:
# 直接根据数据创建
x = torch.tensor([5.5, 3])
print(x)

# 通过提供包含数值的python列表创建Tensor
tp = torch.tensor([[[2, 1, 4, 3], [1, 2, 3 ,4], [4, 3, 2, 1]], [[7, 8, 10, 12], [-1, -3, -5, 13], [1, 4, 6, 8]]])
print(tp)
print(tp.size())

tensor([5.5000, 3.0000])
tensor([[[ 2,  1,  4,  3],
         [ 1,  2,  3,  4],
         [ 4,  3,  2,  1]],

        [[ 7,  8, 10, 12],
         [-1, -3, -5, 13],
         [ 1,  4,  6,  8]]])
torch.Size([2, 3, 4])


In [6]:
# 还可以通过现有的Tensor来创建，此方法会默认重用输入Tensor的一些属性，例如数据类型，除非自定义数据类型
x = x.new_ones(5, 3, dtype=torch.float64)  # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float) # 指定新的数据类型
print(x) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8237, -0.5619, -0.2668],
        [ 1.4587,  1.1159,  0.6411],
        [-0.3077,  0.0846,  0.1844],
        [ 0.3566, -0.6325, -0.7176],
        [ 0.5371,  0.3534, -1.0793]])


In [7]:
# 通过shape或者size()来获取Tensor的形状
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [8]:
# 加法形式一
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.0436, -0.2641,  0.1153],
        [ 1.4896,  1.2841,  1.0436],
        [ 0.4665,  0.7000,  0.4310],
        [ 1.3226, -0.1544, -0.3221],
        [ 1.1848,  0.8209, -1.0435]])


In [9]:
# 加法形式二
print(torch.add(x, y))

tensor([[ 1.0436, -0.2641,  0.1153],
        [ 1.4896,  1.2841,  1.0436],
        [ 0.4665,  0.7000,  0.4310],
        [ 1.3226, -0.1544, -0.3221],
        [ 1.1848,  0.8209, -1.0435]])


In [10]:
# 还可指定输出
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.0436, -0.2641,  0.1153],
        [ 1.4896,  1.2841,  1.0436],
        [ 0.4665,  0.7000,  0.4310],
        [ 1.3226, -0.1544, -0.3221],
        [ 1.1848,  0.8209, -1.0435]])


In [11]:
# 加法形式三
# adds x to y
y.add_(x)
print(y)
# PyTorch操作inplace版本都有后缀_, 例如x.copy_(y), x.t_()

tensor([[ 1.0436, -0.2641,  0.1153],
        [ 1.4896,  1.2841,  1.0436],
        [ 0.4665,  0.7000,  0.4310],
        [ 1.3226, -0.1544, -0.3221],
        [ 1.1848,  0.8209, -1.0435]])


In [12]:
# 可以使用类似NumPy的索引操作来访问Tensor的一部分，需要注意的是：索引出来的结果与原数据共享内存，
# 也即修改一个，另一个会跟着修改
print(x)
y = x[0, :]  # 第一行(0 表示第一行，: 表示所有列)
print(y)
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了
# 选择第 3 维度（列）中的第 2 个索引
z = torch.index_select(x, 1, torch.tensor([2]))
print(z)

tensor([[ 0.8237, -0.5619, -0.2668],
        [ 1.4587,  1.1159,  0.6411],
        [-0.3077,  0.0846,  0.1844],
        [ 0.3566, -0.6325, -0.7176],
        [ 0.5371,  0.3534, -1.0793]])
tensor([ 0.8237, -0.5619, -0.2668])
tensor([1.8237, 0.4381, 0.7332])
tensor([1.8237, 0.4381, 0.7332])
tensor([[ 0.7332],
        [ 0.6411],
        [ 0.1844],
        [-0.7176],
        [-1.0793]])


In [13]:
# 用view()来改变Tensor的形状
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())
print(x.numel(), y.numel(), z.numel())  # numel()返回元素个数

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])
15 15 15


In [14]:
# 注意view()返回的新Tensor与源Tensor虽然可能有不同的size，但是是共享data的，也即更改其中的一个，另外一个也会跟着改变。
# (顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变
x += 1
print(x)
print(y) # 也加了1

tensor([[ 2.8237,  1.4381,  1.7332],
        [ 2.4587,  2.1159,  1.6411],
        [ 0.6923,  1.0846,  1.1844],
        [ 1.3566,  0.3675,  0.2824],
        [ 1.5371,  1.3534, -0.0793]])
tensor([ 2.8237,  1.4381,  1.7332,  2.4587,  2.1159,  1.6411,  0.6923,  1.0846,
         1.1844,  1.3566,  0.3675,  0.2824,  1.5371,  1.3534, -0.0793])


In [15]:
# 如果我们想返回一个真正新的副本（即不共享data内存）该怎么办呢？
# 推荐先用clone创造一个副本然后再使用view
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)
# 使用clone还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源Tensor

tensor([[ 1.8237,  0.4381,  0.7332],
        [ 1.4587,  1.1159,  0.6411],
        [-0.3077,  0.0846,  0.1844],
        [ 0.3566, -0.6325, -0.7176],
        [ 0.5371,  0.3534, -1.0793]])
tensor([ 2.8237,  1.4381,  1.7332,  2.4587,  2.1159,  1.6411,  0.6923,  1.0846,
         1.1844,  1.3566,  0.3675,  0.2824,  1.5371,  1.3534, -0.0793])


In [16]:
# 另外一个常用的函数就是item(), 它可以将一个标量Tensor转换成一个Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.5774])
1.5773797035217285


In [17]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 4, 3, 2])
print(x + y, x - y, x * y, x / y, x ** y)

print(torch.exp(x))  # e^x
print(torch.sin(x))  # sin(x)

tensor([ 3.,  6.,  7., 10.]) tensor([-1., -2.,  1.,  6.]) tensor([ 2.,  8., 12., 16.]) tensor([0.5000, 0.5000, 1.3333, 4.0000]) tensor([ 1., 16., 64., 64.])
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])
tensor([ 0.8415,  0.9093, -0.7568,  0.9894])


In [18]:
# arange函数用于生成一个包含从起始值到结束值（不包括结束值）之间的等间隔值的一维张量
# 生成从0到10（不包括10），步长为1的张量
a = torch.arange(0, 10, 1)
print(a)

# 生成从1到10（不包括10），步长为2的张量
b = torch.arange(1, 10, 2)
print(b)

c = torch.arange(12)
print(c)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 3, 5, 7, 9])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [19]:
# 我们也可以把多个张量连结在一起, dim=0表示按行连结，dim=1表示按列连结
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((x, y), dim=0))
torch.cat((x, y), dim=1)

print(x == y)

# 对张量中的所有元素求和得到只有一个元素的张量(此处转换为标量)
print(x.sum().item())

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
66.0


In [20]:
# 当对两个形状不同的Tensor按元素运算时，
# 可能会触发广播（broadcasting）机制：先适当复制元素使这两个Tensor形状相同后再按元素运算
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a, b)
print(a + b)

# 另一个例子：由于x和y分别是1行2列和3行1列的矩阵，如果要计算x + y，
# 那么x中第一行的2个元素被广播（复制）到了第二行和第三行，
# 而y中第一列的3个元素被广播（复制）到了第二列。
# 如此，就可以对2个3行2列的矩阵按元素相加
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)


tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])
tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [21]:
# 可以用[-1]来访问最后一个元素，[-2]访问倒数第二个元素, 可以用[1:3]来访问第2个和第3个元素
x = torch.arange(12).reshape(3, 4)
print(x[-1])
print(x[1:3])
print()
# 除读取外，我们还可以通过指定索引来将元素写入矩阵
x[1, 2] = 9
print(x)
print()

# 如果我们想为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值
# 例如[0:2, :]访问第1行和第2行，其中“:”代表沿轴1（列）的所有元素
x[0:2, :] = 12
print(x)

tensor([ 8,  9, 10, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])


In [22]:
# 索引操作是不会开辟新内存的，而像y = x + y这样的运算是会新开内存的，然后将y指向新内存。
# 为了演示这一点，我们可以使用Python自带的id函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before) # False 

# 如果想指定结果到原来的y的内存，我们可以使用前面介绍的索引来进行替换操作
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before) # True

# 我们还可以使用运算符全名函数中的out参数或者自加运算符+=(也即add_())达到上述效果，
# 例如torch.add(x, y, out=y)和y += x(y.add_(x))
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before) # True

False
True
True


In [23]:
# 使用from_numpy()将NumPy数组转换成Tensor，使用.numpy()将Tensor转换成NumPy数组
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(type(a), type(b))
print(a, b)

a += 1
print(a, b)

b += 1
print(a, b)

<class 'numpy.ndarray'> <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [24]:
# 将大小为1的张量转换为Python的标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [25]:
# 用方法to()可以将Tensor在CPU和GPU（需要硬件支持）之间相互移动
# 以下代码只有在PyTorch GPU版本上才会执行
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改

tensor([[2, 3, 4],
        [5, 6, 7]], device='cuda:0')
tensor([[2., 3., 4.],
        [5., 6., 7.]], dtype=torch.float64)
